# Generated by Django 5.2.5 on 2025-12-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prayer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="iso_code",
            field=models.CharField(
                help_text="Código ISO-3166 alpha-3 (ej: ARG, USA, BRA)",
                max_length=3,
                unique=True,
            ),
        ),
    ]
