# Generated by Django 5.2.5 on 2026-01-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prayer_board", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="familygroup",
            name="last_prayed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="familygroup",
            name="prayed_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
