# Generated by Django 5.2.5 on 2026-01-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prayer_board", "0002_familygroup_last_prayed_at_familygroup_prayed_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="familygroup",
            name="last_prayed_at",
        ),
        migrations.RemoveField(
            model_name="familygroup",
            name="prayed_count",
        ),
        migrations.AddField(
            model_name="prayerrequest",
            name="last_prayed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prayerrequest",
            name="prayed_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
