# Generated by Django 5.2.5 on 2026-01-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prayer_board", "0003_remove_familygroup_last_prayed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prayerrequest",
            name="answered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prayerrequest",
            name="is_answered",
            field=models.BooleanField(default=False),
        ),
    ]
