# Generated by Django 5.2.5 on 2026-01-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prayer_board", "0004_prayerrequest_answered_at_prayerrequest_is_answered"),
    ]

    operations = [
        migrations.AddField(
            model_name="familygroup",
            name="access_code",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="familygroup",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
    ]
