# Generated by Django 5.2.5 on 2026-01-13 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prayer_board", "0005_familygroup_access_code_familygroup_is_private"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrayerComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prayer_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="prayer_board.prayerrequest",
                    ),
                ),
            ],
        ),
    ]
